name: cron-job
on:
  schedule:
    - cron: "0,30 6-22 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request GET \
          --url '${{ secrets.NETLIFY_API_ENDPOINT }}'
